lib/pact/cli.rb
lib/pact/cli/generate_pact_docs.rb

- Exposed Pact docs generation to a thor command
- Using default i/o locations (./pacts and ./doc/pact respectively)
- Markdown renderer is hardcoded atm

Pact CLI docs feature basic implementation

---

lib/pact/cli.rb
lib/pact/cli/run_pact_verification.rb
lib/pact/provider/configuration/pact_verification.rb
lib/pact/provider/pact_repository_uri.rb
lib/pact/provider/pact_source.rb
lib/pact/provider/rspec.rb
lib/pact/tasks/task_helper.rb
spec/lib/pact/provider/configuration/pact_verification_spec.rb
spec/lib/pact/provider/configuration/service_provider_dsl_spec.rb
spec/lib/pact/provider/pact_repository_uri_spec.rb
spec/lib/pact/tasks/task_helper_spec.rb

Hi,
I've forked the pact, pact-support and pact_broker-client repository and made the changes on the 'basic_auth' branch for each project and created pull request.
The main changes are:
pass the basic auth option to PactFile open method
* added the basic auth options in dsl 
```ruby
honours_pact_with 'ServiceConsumer' do
pact_uri 'http://pact-broker-url/consumer/ServiceConsumer/latest', {username: 'user', password: 'pass'}
end
```
* when running pact:verify:at['pact_broker_url'] task, currently I just let users to set environment variables PACT_REPO_USERNAME, PACT_REPO_PASSWORD for the basic auth information.  I am not sure whether it's good enough.
pass optional pact_broker_basic_auth in the PublicationTask
```ruby
task.pact_broker_basic_auth =  { username: 'basic_auth_user', password: …
```

Basic auth

---

lib/pact/consumer/configuration/mock_service.rb

Access for `name` will not work.

Fix minor validation bug

---

documentation/configuration.md

Add document about new `pactfile_write_mode` option. https://github.com/bethesque/pact-mock_service/commit/f2f87704ce68207b99621ba0072a7c3129569aaa#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR7

Update document about pactfile_write_mode

---

lib/pact/doc/markdown/interaction_renderer.rb

Missing 'erb' caused `NameError` in `spec/integration/cli_docs_spec.rb` which does not affect example failure though.
ref: https://travis-ci.org/realestate-com-au/pact/jobs/89347236#L922

Load missing dependent library

---

.travis.yml

As same as https://github.com/bethesque/pact-support/pull/16, https://github.com/bethesque/pact-support/pull/17, run CI with new Rubies.

Update Travis CI setting with new Rubies

---

lib/pact/consumer/configuration/mock_service.rb
pact.gemspec
spec/lib/pact/consumer/configuration_spec.rb

By https://github.com/bethesque/pact-mock_service/pull/43,
pact-mock_service can find and use available port on machine automatically,
we can configure Pact's mock service without port configuration, and it should
mean the mock service obtains available port automatically.
~~~Feature work: Now we can define mock service without any configuration
but still have to call `mock_service` DSL method with empty block:~~~
```ruby
Pact.service_consumer 'ConsumerApp' do
has_pact_with 'ProviderApp' do
mock_service(:provider_app) {}
end
end
```
***[update]*** This feature work will be resolved by https://github.com/bethesque/pact-support/pull/20.

Add interface to use find_available_port option

---

documentation/configuration.md
lib/pact/cli.rb
lib/pact/consumer/configuration/configuration_extensions.rb
lib/pact/provider/configuration/configuration_extension.rb
lib/pact/provider/pact_spec_runner.rb
lib/pact/version.rb
pact.gemspec
spec/lib/pact/provider/pact_spec_runner_spec.rb

Add ability to configure interactions replay order. Default value: 'randomised'

Randomise contract interactions

---

lib/pact/tasks/task_helper.rb

`--backtrace` option appears twice.
```
$ rake pact:verify BACKTRACE=true
SPEC_OPTS='' ruby -S pact verify --pact-helper /path/to/pact_helper.rb --backtrace --backtrace
```

remove duplicated `--backtrace` option

---

lib/pact/doc/markdown/interaction_renderer.rb
spec/lib/pact/doc/markdown/consumer_contract_renderer_spec.rb
spec/spec_helper.rb
spec/support/generated_markdown.md
spec/support/markdown_pact.json
spec/support/warning_silencer.rb

I faced Encoding::CompatibilityError recently in pact-broker.
The rendered string will be joined with strings who's encoding will be
script encoding.
ruby's default script encoding is UTF-8. In some environments, ruby's
default external encoding will be ASCII-8BIT. It depends system
configuration which we, library developers, can't handle. In that case
Pact::Doc::Markdown::ConsumerContractRenderer#call trys to join UTF-8
strings with non UTF-8 string. It raises Encoding::CompatibilityError.
(below pry session shows encoding difference and error)
pry(#<Pact::Doc::Markdown::ConsumerContractRenderer>)> [title, summaries_title, summaries.join, interactions_title, full_interactions.join].map {|e| e.encoding }
=> [#<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>, #<Encoding:UTF-8>, …

Fix Encoding::CompatibilityError in markdown renderer

---

pact.gemspec

This gem shouldn't be included as a production dependency.

move awesome_print dependency to development

---

documentation/configuration.md
lib/pact/provider/configuration/configuration_extension.rb
spec/lib/pact/provider/configuration/configuration_extension_spec.rb

Fix bug in default interactions replay order
* Fix `:recorer` vs `:recorded` incosistency in favour of `:recorded`
with reliance on the spec
* Otherwise default was actually non-expected `:random` because of
```
def ordered_pact_json(pact_json)
return pact_json if Pact.configuration.interactions_replay_order == :recorded
consumer_contract = JSON.parse(pact_json)
consumer_contract["interactions"] = consumer_contract["interactions"].shuffle
consumer_contract.to_json
end
```

Fix bug in default interactions replay order

---

lib/pact/consumer/consumer_contract_builder.rb
spec/lib/pact/consumer/consumer_contract_builder_spec.rb

Check the interaction is defined correctly here. If the interaction is
not defined correctly, that can cause errors in pact verification in
Provider test. For example, "undefined method `capitalize' for
nil:NilClass" at `#interaction_description_for_rerun_command`.
I sent follow up PR to pact-support repository: https://github.com/bethesque/pact-support/pull/24

Raise an error when the interaction is invalid

---

README.md

Somehow the date changed and therefore the URL broke.

Fix link to Ron Holshausen's blog post

---

lib/pact/provider/rspec.rb
spec/integration/consumer_with_params_hash_spec.rb
spec/lib/pact/consumer/consumer_contract_builder_spec.rb
spec/lib/pact/provider/configuration/pact_verification_spec.rb
spec/lib/pact/provider/configuration/service_provider_dsl_spec.rb
spec/lib/pact/provider/help/console_text_spec.rb
spec/lib/pact/provider/help/content_spec.rb
spec/lib/pact/provider/help/pact_diff_spec.rb
spec/lib/pact/provider/matchers/messages_spec.rb
spec/lib/pact/provider/pact_helper_locator_spec.rb
spec/lib/pact/provider/pact_uri_spec.rb
spec/lib/pact/provider/print_missing_provider_states_spec.rb
spec/lib/pact/provider/request_spec.rb
spec/lib/pact/provider/rspec_spec.rb
spec/lib/pact/provider/state/provider_state_proxy_spec.rb
spec/lib/pact/provider/state/provider_state_spec.rb
spec/support/shared_examples_for_request.rb

- Use ruby 2.0 hash syntax
- Remove redundant hash curly braces for params
- Sensible new line and spacing

Code style clean up for specs.

---

README.md

This PR changes the Travis build badge to point at `master` to show _its_ build status.

README: Travis badge to show status on master branch

---

README.md

Currently all the documentation wiki links in README point to broken old location. This PR fixes that. I think this might be good interim solutions.
Let me know if these links needs to be replaced by docs.pact.io or some thing.
By the way awesome project.

Fixing the broken wiki links in Readme

---

README.md

Old link went to previous repository, this PR corrects the link to this repository's Travis Build

docs(README): correct Travis build link

---

lib/pact/provider/rspec.rb

Spotted this, which is preventing verification from working correctly on a v3 message pact.

fix(message): message body content should be 'contents'

---

lib/pact/hal/entity.rb
lib/pact/hal/http_client.rb
lib/pact/hal/link.rb
lib/pact/pact_broker/fetch_pacts.rb
lib/pact/provider/verification_results/publish.rb
lib/pact/provider/verification_results/verification_result.rb
spec/lib/pact/hal/entity_spec.rb
spec/lib/pact/hal/http_client_spec.rb
spec/lib/pact/hal/link_spec.rb
spec/lib/pact/pact_broker/fetch_pacts_spec.rb
spec/lib/pact/provider/verification_results/publish_spec.rb

This PR is using HAL Client which got introduced in [hypermedia-client branch](https://github.com/pact-foundation/pact-ruby/tree/feat/hypermedia-client) and hence cannot be merged before that.

feat: Dynamically retrieve pacts for a given provider

---

README.md
documentation/README.md

* Fix spaces with link to `Testing with pact.png`
* Fix incorrect link to `News, blogs, videos and articles`

Organize links to the wiki

---

lib/pact/provider/test_methods.rb
lib/pact/version.rb

Ensure that global and base states are executed regardless of
whether interaction defines a provider state, as described in
the docs.
Fixes #180

fix: always execute global and base states

---

pact.gemspec

Currently, the metadata links on [Rubygems](https://rubygems.org/gems/pact) point to the old `pact` repository.
This PR fixes that by specifying them in the gemspec. They will be updated the next  time a new  version of `pact` is pushed.

Add metadata links to gemspec

---

lib/pact/provider/pact_helper_locator.rb
spec/lib/pact/provider/pact_helper_locator_spec.rb

For us Minitest users, the lack of `test/...` paths in `PACT_HELPER_FILE_PATTERNS` causes `PactHelperLocator` to locate [this pact_helper.rb of the pact_broker-client](https://github.com/pact-foundation/pact_broker-client/blob/master/spec/service_providers/pact_helper.rb) before the actual `pact_helper.rb` file inside the `test` dir. 😨

Add 'test' dir to pact_helper_locator file patterns

---

pact.gemspec

* Drop unnecessary encoding pragma
* Use short form `__dir__`
* Add changelog
* Drop unnecessary `json` requirement
* Require `pry-byebug` for development

chore: update gemspec

---

README.md

Reverts pact-foundation/pact-ruby#126 — after a long time I checked the link again, and apparently the blog owner has updated the dates, so now the old link is working again.

Revert "Fix link to Ron Holshausen's blog post"

---

lib/pact/consumer/consumer_contract_builder.rb
lib/pact/consumer/interaction_builder.rb
spec/lib/pact/consumer/interaction_builder_spec.rb

This allows to call `without_writing_to_pact` when adding expectations to the mock service so that the interaction will have metadata with `write_to_pact: false` and the mock service will know to not write the interaction to the pact file.
```ruby
my_service
.without_writing_to_pact # <= New
.given('...')
.upon_receiving('A request to..')
.with(..)
.will_respond_with(...)
```

Set expected interactions on mock service without writing them to pact file

---

lib/pact/provider/configuration/message_provider_dsl.rb
spec/lib/pact/provider/configuration/message_provider_dsl_spec.rb

Regarding the issue #215 this PR propose a solution for it.
IMO it's not the best solution but I couldn't find anything to append a method in a block.
I'm open to new ideas of how to improve it :)

Fix integration with pact-message-ruby

---

pact.gemspec

Reverts pact-foundation/pact-ruby#219

Revert "fix: bump rake dependency per CVE-2020-8130"

---

lib/pact/cli.rb
pact.gemspec

Thor `1.0` is out, and we're using it with Pact on https://github.com/department-of-veterans-affairs/vets-api.
But we're having to maintain a fork to do so. This PR bumps the Thor dependency with a `< 2.0` max, imitating recent versions of Railties.
Feedback is welcome. Thank you!

Update thor dependency

---

lib/pact/provider/pact_uri.rb
spec/lib/pact/provider/pact_uri_spec.rb

Uris like https://pat@my-pact-server/pact.json are correct, where pat stands for personal access token, and is a secret.
=> the pat should not be exposed in logs [here ](https://github.com/pact-foundation/pact-ruby/blob/3cd57cb342ce17211edbb6c0c6ed5d36879cdbf9/lib/pact/provider/rspec.rb#L26)
It would be more elegant to not implictly consider the 'username' as 'pat' when there is no password, and maybe create another explicit property in the class, but i was not sure to control the impacts of such a change... (First commit ever in ruby :) ).
And after some digging arround, i'm not even sure it would worth it.
Please let me know if you think otherwise though.

fix(security): hide personal access token given in uri

---

lib/pact/pact_broker/pact_selection_description.rb
spec/lib/pact/pact_broker/pact_selection_description_spec.rb

As described [here](https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors/#properties), we can fetch pacts filtering them by consumer name. When the `consumer_version_selectors` specifies a consumer name, there is no information about it in the pact fetching description so one can think it does not work.
Bonus: the `latest` variable was unused so I removed it. I'm wondering what was the idea behind it, maybe it should be used in the end?

fix: add consumer name to the selection description

---

pact.gemspec

Recently we have updated the pact-support gem to remove the randexp dependency. In order to get that change in pact, I am updating the pact-support version in this PR.
pact-support PR - https://github.com/pact-foundation/pact-support/pull/91 
cc: @bethesque

fix: updating pact-support dependency version

---

lib/pact/provider/configuration/service_provider_config.rb
lib/pact/provider/configuration/service_provider_dsl.rb
lib/pact/provider/verification_results/create.rb
lib/pact/provider/verification_results/verification_result.rb
spec/integration/publish_verification_spec.rb
spec/lib/pact/provider/configuration/service_provider_config_spec.rb
spec/lib/pact/provider/configuration/service_provider_dsl_spec.rb
spec/lib/pact/provider/verification_results/create_spec.rb

Thanks for the awesome project!
This PR adds a configuration option to add buildUrl into verification results, which could be added later as a [webhook param](https://github.com/pact-foundation/pact_broker/commit/17463b1664c2ae1949ad1c98021198160d598ef5) in pact broker.

feat: Provide configuration for build url to be published in verification results

---

lib/pact/provider/configuration/message_provider_dsl.rb
lib/pact/provider/configuration/service_provider_dsl.rb
lib/pact/provider/pact_uri.rb
lib/pact/provider/state/provider_state.rb

```
…/configuration/service_provider_dsl.rb:67: warning: `&' interpreted as argument prefix
…/pact_uri.rb:6: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
…/configuration/message_provider_dsl.rb:49: warning: `&' interpreted as argument prefix
…/state/provider_state.rb:15: warning: `&' interpreted as argument prefix
…/state/provider_state.rb:19: warning: `&' interpreted as argument prefix
…/state/provider_state.rb:63: warning: assigned but unused variable - fullname
…/state/provider_state.rb:84: warning: `&' interpreted as argument prefix
…/state/provider_state.rb:88: warning: `&' interpreted as argument prefix
```

Fixup ruby warnings

---

.github/workflows/test.yml

* use setup-ruby to run bundle install
* refactor `BUNDLE_GEMFILE` to the job level
Test runs with these changes can be observed here - https://github.com/josephyi/pact-ruby/actions/workflows/test.yml

feat(CI): use setup-ruby's bundle installer and cache

---

Gemfile
lib/pact/provider/help/console_text.rb
lib/pact/provider/help/prompt_text.rb
lib/pact/provider/matchers/messages.rb
lib/pact/provider/print_missing_provider_states.rb
lib/pact/provider/rspec/formatter_rspec_2.rb
lib/pact/provider/rspec/formatter_rspec_3.rb
lib/pact/provider/rspec/pact_broker_formatter.rb
lib/tasks/pact.rake
pact.gemspec
spec/lib/pact/provider/matchers/messages_spec.rb
spec/support/cli.rb
tasks/pact-test.rake

The `term-ansicolor` gem injects a global `Term` module that has a high probability of naming collision for other common class names. This PR replaces that gem with the `rainbow` gem to avoid this issue.

refactor: replace ansicolor gem with rainbow to avoid naming collisions

---

lib/pact/provider/help/console_text.rb
lib/pact/provider/help/prompt_text.rb
lib/pact/provider/matchers/messages.rb
lib/pact/provider/print_missing_provider_states.rb
lib/pact/provider/rspec/formatter_rspec_2.rb
lib/pact/provider/rspec/formatter_rspec_3.rb
lib/pact/provider/rspec/pact_broker_formatter.rb
lib/tasks/pact.rake
pact.gemspec
spec/lib/pact/provider/matchers/messages_spec.rb
spec/support/cli.rb
tasks/pact-test.rake

Reverts pact-foundation/pact-ruby#254
This is causing build failures, but I can't replicate locally at the moment on my m1 mac, so will revert and relook this again

Revert "refactor: replace ansicolor gem with rainbow to avoid naming collisions"

---

pact.gemspec

Webrick was originally part of the pact application, but is now purely used to support testing.
Also, to quote Jeremy Evans https://github.com/ruby/webrick/issues/145#issuecomment-2359963761
> Webrick has not been part of Ruby since the release of Ruby 3.0, over three years ago. While this repository is under the ruby organization on GitHub, it is no longer considered part of Ruby.
>
> Webrick should not be used in production. It is only still maintained because there are other gems relying it, most of which do so only for testing, and only because it is a pure ruby implementation and it was shipped with Ruby in the past.
As Webrick has recently seen a number of CVEs, pulling Webrick in to other codebases unecessarily causes security related maintenance.
It's still fine for testing.

refactor(dependencies): Move webrick to be a pure development dependency.

---

.github/workflows/test.yml
example/animal-service/Gemfile.lock
example/zoo-app/Gemfile.lock
lib/pact/provider/request.rb

Cuon kakimoto fix/sinatra 4 1 x host

---

lib/pact/provider/request.rb

https://github.com/pact-foundation/pact-ruby/pull/327 is related.
The rspec test for the Zoo App and Animal Service failed because of an incorrect header.
The rspec result is as follows:
```
2) Verifying a pact between Zoo App and Animal Service Given there is an alligator named Mary a request for an alligator with GET /alligators/Mary returns a response which has a matching body
Failure/Error: expect(response_body).to match_term expected_response_body, diff_options, example
Actual: Host not permitted
```
The log is as follows:
```
I, [2025-01-11T08:27:26.148896 #1865]  INFO -- : Sending GET request to path: "/alligators/Mary" with headers: {"HTTP_HTTP_HOST"=>"localhost", "HTTP_ACCEPT"=>"application/json"}, see debug logs for body
```
`HTTP_HTTP_HOST` is not correct, `HTTP_HOST` is …

FIX: HTTP_HOST headers.
